CREATE TABLE employees (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_number VARCHAR NOT NULL,
    full_name VARCHAR NOT NULL,
    gender VARCHAR NOT NULL,
    birth_place VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    religion VARCHAR NOT NULL,
    marital_status VARCHAR NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    identify_card_number BIGINT NOT NULL,
    join_date TIMESTAMP,
    end_date TIMESTAMP,
    is_activated BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    created_by VARCHAR,
    updated_at TIMESTAMP,
    updated_by VARCHAR
);
